/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebSearchRouteImport } from './routes/api/web-search'
import { Route as ApiSarvamTtsRouteImport } from './routes/api/sarvam-tts'
import { Route as ApiSarvamSttRouteImport } from './routes/api/sarvam-stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSarvamTtsRoute = ApiSarvamTtsRouteImport.update({
  id: '/api/sarvam-tts',
  path: '/api/sarvam-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSarvamSttRoute = ApiSarvamSttRouteImport.update({
  id: '/api/sarvam-stt',
  path: '/api/sarvam-stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sarvam-stt': typeof ApiSarvamSttRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sarvam-stt': typeof ApiSarvamSttRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/sarvam-stt': typeof ApiSarvamSttRoute
  '/api/sarvam-tts': typeof ApiSarvamTtsRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/sarvam-stt'
    | '/api/sarvam-tts'
    | '/api/web-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/sarvam-stt'
    | '/api/sarvam-tts'
    | '/api/web-search'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/sarvam-stt'
    | '/api/sarvam-tts'
    | '/api/web-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSarvamSttRoute: typeof ApiSarvamSttRoute
  ApiSarvamTtsRoute: typeof ApiSarvamTtsRoute
  ApiWebSearchRoute: typeof ApiWebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sarvam-tts': {
      id: '/api/sarvam-tts'
      path: '/api/sarvam-tts'
      fullPath: '/api/sarvam-tts'
      preLoaderRoute: typeof ApiSarvamTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sarvam-stt': {
      id: '/api/sarvam-stt'
      path: '/api/sarvam-stt'
      fullPath: '/api/sarvam-stt'
      preLoaderRoute: typeof ApiSarvamSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSarvamSttRoute: ApiSarvamSttRoute,
  ApiSarvamTtsRoute: ApiSarvamTtsRoute,
  ApiWebSearchRoute: ApiWebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
